# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Colella
email: colella.john@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John Colella Portfolio. Full Stack developer building apps with React and Rails.
baseurl: "" # the subpath of your site, e.g. /blog
url: "john-colella.com" # the base hostname & protocol for your site
# twitter_username: jcolella48
github_username:  jmcolella
linkedin_username: johnmcolella
instagram_username: beerpants

# Build settings
markdown: kramdown
