# Site settings
title: John Colella
email: colella.john@gmail.com
url: https://example.github.io
description: "full stack web developer residing in Brooklyn, NY"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fff'
  links: '#6fbf64'

# Footer settings
footer: John Colella

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/johnmcolella
  - title: github
    url: https://github.com/jmcolella

# Build settings
markdown: kramdown
permalink: pretty
