# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Colella
email: colella.john@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a full stack web developer with experience using Ruby, JavaScript, Rails, Bootstrap, Materialize and Jekyll. Built using Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jcolella48
linkedin_username: johnmcolella
github_username:  jmcolella

# Build settings
markdown: kramdown

